spring:
  application:
    name: concertseat
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${PROFILE}

  datasource:
    driver-class-name: ${DB_DRIVER}
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_updates: true
        order_inserts: true

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "${BASE_URL}/api/auth/oauth2/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname
            client-name: kakao
          twitter:
            client-id: ${TWITTER_CLIENT_ID}
            client-secret: ${TWITTER_CLIENT_SECRET}
            redirect-uri: "${BASE_URL}/api/auth/oauth2/twitter"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: users.read
            provider: twitter
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          twitter:
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token
            user-info-uri: https://api.twitter.com/2/users/me
            user-name-attribute: id
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${S3_ACCESSKEY}
      secretKey: ${S3_SECRETKEY}

server:
  tomcat:
    max-http-form-post-size: 30MB

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION}
