spring:
  application:
    name: concertseat
  config:
    import: optional:file:.env[.properties]

  profiles:
    active: ${PROFILE}

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: "${BASE_URL}/api/auth/oauth2/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: account_email, profile_nickname
            client-name: kakao
          twitter:
            client-id: ${TWITTER_CLIENT_ID}
            client-secret: ${TWITTER_CLIENT_SECRET}
            redirect-uri: "${BASE_URL}/api/auth/oauth2/twitter"
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            scope: users.read, tweet.read, offline.access
            provider: twitter
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          twitter:
            authorization-uri: https://twitter.com/i/oauth2/authorize
            token-uri: https://api.twitter.com/2/oauth2/token
            user-info-uri: https://api.twitter.com/2/users/me?user.fields=id,name,username,profile_image_url
            user-name-attribute: id

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
    expiration: ${JWT_ACCESS_EXPIRATION}
  refresh:
    secret: ${JWT_REFRESH_SECRET}
    expiration: ${JWT_REFRESH_EXPIRATION}
